### ISSUE TITLE
ModuleNotFoundError: No module named 'pmcyg'

### ISSUE THREAD

**Issue by RichieB2B** [rwpenney/pmcyg#2]
When using `pip3` I can only install `pmcyg-2.4.2.tar.gz` because `pmcyg-3.2.0.tar.gz` and `pmcyg-3.0.tar.gz` error out:

```
$ pip3 install pmcyg
Collecting pmcyg
  Downloading pmcyg-3.2.0.tar.gz (59 kB)
     |████████████████████████████████| 59 kB 6.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpnz84suby_in_process.py get_requires_for_build_wheel /tmp/tmpajvyplpj
       cwd: /tmp/pip-install-rdc0gni7/pmcyg_e4f987bdf8be4130a3695e2e207d2661
  Complete output (15 lines):
  Traceback (most recent call last):
    File "/tmp/tmpnz84suby_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpnz84suby_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpnz84suby_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-n8r2_hzv/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-n8r2_hzv/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-n8r2_hzv/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 7, in <module>
  ModuleNotFoundError: No module named 'pmcyg'

```

**Comment by RichieB2B** [comment]
Probably caused by https://github.com/pypa/pip/issues/12030

**Comment by RichieB2B** [comment]
Indeed, it is a bug in `pip`. Closing now.

**Comment by RichieB2B** [comment]
As explained [here](https://github.com/pypa/pip/issues/12030#issuecomment-1587809416) this is considered a bug in `setup.py`. I'll make a PR.

**Comment by paweljasinski** [comment]
could you please make a release of 3.2.1 to pypi.
For poor souls like me, it is still broken ...

**Comment by rwpenney** [comment]
Thanks for the nudge, @paweljasinski  - [pmcyg-3.2.2 should now be visible](https://pypi.org/project/pmcyg/#history) on pypi, including the '--generate-replica' fix that you've found.
