### ISSUE TITLE
error when trying to do replica

### ISSUE THREAD

**Issue by paweljasinski** [rwpenney/pmcyg#4]
```
$ /bin/python pmcyg.py -A x86_64 -R replica
Traceback (most recent call last):
  File "/home/rejap/github/pmcyg/pmcyg.py", line 20, in <module>
    main()
  File "/home/rejap/github/pmcyg/pmcyg/command_line.py", line 119, in main
    if not HOST_IS_CYGWIN:
NameError: name 'HOST_IS_CYGWIN' is not defined
```

And the dirty fix:
```
$ diff pmcyg/command_line.py~ pmcyg/command_line.py
7c7
< from .core import PMbuilder
---
> from .core import PMbuilder, HOST_IS_CYGWIN
```

**Comment by rwpenney** [comment]
Thanks for spotting that. This should now be fixed in 747661832ac6fc3fee06ace19378cf0b668ed3f7.
